### ISSUE TITLE
`saplingsOnly` config doesn't work

### ISSUE THREAD

**Issue by MelanX** [KyleBCox/TwerkItMeal#20]
### Versions
Minecraft: `1.19`
Forge: `41.0.98`
TwerkItMeal: `2.2.1`

### How to reproduce
1. Set `saplingsOnly` in config to `true`. 
2. Place some crops.
3. Twerk a bit (ingame).
4. Crops are still growing.

### Additional information
Maybe I did something wrong? Maybe I forgot to change other config values? Here's the complete config:
```toml
#When true only saplings are allowed to grow with twerking
saplingsOnly = true
#The chance of growth effect being applied from sprinting
#Range: 0.0 ~ 1.0
sprintGrowChance = 0.001
#The chance of growth effect being applied from any source
#Range: 0.0 ~ 1.0
crouchGrowChance = 0.5
#Whether to show particles or not when crouching to grow things
showParticles = true
#whether to enable the whitelist this does not disable the blacklist
useWhiteList = false
#growables to disable crouching on
blacklist = ["minecraft:netherrack", "minecraft:grass_block", "minecraft:warped_nylium", "minecraft:crimson_nylium", "minecraft:tall_grass", "minecraft:grass", "botanypots", "gaiadimension"]
#growables to enable crouching on (only works if 'useWhiteList' is true and will give exclisivity to those growables) 
whitelist = []
#the minimum number of crouches before the bonemeal is applied (bonemeal is applied randomly so this will not be exact)
#Range: > 0
minCrouchesToApplyBonemeal = 5
#The radius of effect in blocks of applying the growth effect. Not recommended to change due to performance.
#Range: 0 ~ 20
effectRadius = 5
```
